### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by philipvandebriel** [emizentech/magento2-category-list-widget#1]
Hi,

Try to install the module but get the next error, can you fix it ?

Invalid XML in file /var/www/clients/client1/web1/web/app/code/Emizentech/CategoryWidget/etc/widget.xml:
Element 'label', attribute 'translate': '' is not a valid value of the atomic type 'xs:boolean'.
Line: 14

Element 'parameter', attribute 'value': The attribute 'value' is not allowed.
Line: 18

Element 'parameter', attribute 'value': The attribute 'value' is not allowed.
Line: 22

Thx for the module,

Best Regards,

Philip

**Comment by emizentech** [comment]
Hello Philip

Can we get the access where you are trying to install it 

Amit

**Comment by philipvandebriel** [comment]
Hi Amit,

Sorry this is not possible, can you give us a hint what we can do to try ?

line 14 =    <label translate="">With Image</label>
line 18 =  <parameter name="imagewidth" xsi:type="text"  visible="true" sort_order="2" value="250">
line 22 = <parameter name="imageheight" xsi:type="text"  visible="true" sort_order="3" value="250">

Philip

**Comment by emizentech** [comment]
Hello Philip,

Kindly Pull the latest update, and let me know if you are still getting the issue 
we have updated the xml file

Thanks 
Amit

**Comment by philipvandebriel** [comment]
Hi Amit,

Thx work great ! Just what we need,

Best Regards,

Philip
