### ISSUE TITLE
Fatal error: Class CategoryWidget  not found

### ISSUE THREAD

**Issue by dinofratelli** [emizentech/magento2-category-list-widget#3]
I have this error after I include the widget to my homepage http://ibamboli.enterprise-consulting.ovh/
"Fatal error: Class 'Emizentech\CategoryWidget\Block\Widget\CategoryWidget' not found in /var/www/ibamboli.store/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 105" 

Any idea?

**Comment by IzyPizy** [comment]
Did you check permissions? If file permissions are ok, you need maybe to launch a magento setup:upgrade and then a setup:di:compile (remember to rm -rf var/di/ and var/generation/ before)

**Comment by aaronsturm** [comment]
I had the same problem. I forgot to run `bin/magento setup:upgrade`. Hope that helps you @dinofratelli.
