### ISSUE TITLE
HTTP ERROR 500 - The page isn’t working

### ISSUE THREAD

**Issue by Stevie-Ray** [emizentech/magento2-category-list-widget#5]
Hi emizentech,

First of all thanks for your module! 

After installing this module in Magento 2 I get the following error:

_"The page isn’t working, the page is currently unable to handle this request."_

Commenting [line 71 ](https://github.com/emizentech/magento2-category-list-widget/blob/master/Block/Widget/CategoryWidget.php#L71) of CategoryWidget.php fixes this issue.

`$storecats->addAttributeToSelect('image'); `

**Comment by johnny-longneck** [comment]
Thanks!

**Comment by emizentech** [comment]
kindly check latest commit
